/*
 * File: app/view/OHLCCharts.js
 *
 * This file was generated by Sencha Architect version 4.2.9.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.3.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.3.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Demo.view.OHLCCharts', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.OHLCCharts',

    alternateClassName: [
        'OHLCCharts'
    ],
    requires: [
        'Demo.view.OHLCChartsViewModel',
        'Demo.view.OHLCChartsViewController',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.form.field.Date',
        'Ext.button.Button',
        'Ext.chart.CartesianChart',
        'Ext.chart.axis.Time',
        'Ext.chart.series.CandleStick',
        'Ext.chart.interactions.PanZoom',
        'Ext.chart.interactions.Crosshair'
    ],

    controller: 'ohlccharts',
    viewModel: {
        type: 'ohlccharts'
    },
    dock: 'top',
    height: '100vh',
    padding: 0,
    style: {
        background: '#ffffff'
    },
    width: '100wh',
    layout: 'fit',
    bodyPadding: 0,
    frameHeader: false,
    manageHeight: false,

    dockedItems: [
        {
            xtype: 'toolbar',
            alignTarget: '',
            border: 2,
            dock: 'top',
            style: {
                background: '#c6e4aa'
            },
            layout: {
                type: 'hbox',
                padding: '0 10 0 0'
            },
            items: [
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'textfield',
                    id: 'tickerInput',
                    width: 100,
                    fieldLabel: 'Ticker',
                    labelWidth: 40,
                    value: 'AAPL'
                },
                {
                    xtype: 'datefield',
                    id: 'fromDatePicker',
                    width: 250,
                    fieldLabel: 'From',
                    labelWidth: 50,
                    value: '01/01/2020'
                },
                {
                    xtype: 'datefield',
                    id: 'toDatePicker',
                    resizable: false,
                    width: 250,
                    fieldLabel: 'To',
                    labelWidth: 50,
                    value: '12/31/2020'
                },
                {
                    xtype: 'button',
                    id: 'refreshBtn',
                    text: 'Refresh',
                    listeners: {
                        click: 'onRefreshBtnClick'
                    }
                }
            ]
        },
        {
            xtype: 'cartesian',
            dock: 'top',
            height: '85vh',
            id: 'mycandlestickchart',
            itemId: 'mycandlestickchart',
            margin: '0 0 0 0',
            width: '100vw',
            colors: [
                '#115fa6',
                '#94ae0a',
                '#a61120',
                '#ff8809',
                '#ffd13e',
                '#a61187',
                '#24ad9a',
                '#7c7474',
                '#a66111'
            ],
            store: 'BtcRateDataJsonPStore',
            innerPadding: {
                top: 0,
                left: 10,
                right: 10,
                bottom: 0
            },
            axes: [
                {
                    type: 'time',
                    fields: [
                        'date'
                    ],
                    id: 'bottom',
                    position: 'bottom'
                },
                {
                    type: 'numeric',
                    fields: [
                        'low',
                        'high',
                        'close',
                        'open'
                    ],
                    position: 'left'
                }
            ],
            series: [
                {
                    type: 'candlestick',
                    style: {
                        ohlcType: 'ohlc',
                        barWidth: 10,
                        opacity: 0.9,
                        dropStyle: {
                            fill: 'rgb(237,123,43)',
                            stroke: 'rgb(237,123,43)'
                        },
                        raiseStyle: {
                            fill: 'rgb(55,153,19)',
                            stroke: 'rgb(55,153,19)'
                        }
                    },
                    xField: 'date',
                    closeField: 'close',
                    highField: 'high',
                    lowField: 'low',
                    openField: 'open'
                }
            ],
            interactions: [
                {
                    type: 'panzoom',
                    enabled: false,
                    axes: {
                        left: {
                            allowPan: false,
                            allowZoom: false
                        },
                        bottom: {
                            allowPan: true,
                            allowZoom: true
                        }
                    },
                    zoomOnPan: true
                },
                {
                    type: 'crosshair',
                    axes: {
                        bottom: {
                            label: {
                                fillStyle: 'white'
                            },
                            rect: {
                                fillStyle: '#344459',
                                opacity: 0.7,
                                radius: 5
                            }
                        },
                        left: {
                            label: {
                                fillStyle: 'white'
                            },
                            rect: {
                                fillStyle: '#344459',
                                opacity: 0.7,
                                radius: 5
                            }
                        }
                    }
                }
            ]
        }
    ],
    listeners: {
        afterrender: 'onPanelAfterRender',
        render: 'onPanelRender'
    }

});